# Redis Configuration
redis.host=localhost
redis.port=6379
spring.data.redis.connect-timeout=60000
redis.username=
redis.password=
redis.database=0

# Server Configuration
server.port=8080

# Logging
logging.level.com.energy.monitor=DEBUG
logging.level.redis.clients.jedis=INFO